- cmd/csv2cpe/csv2cpe.go
- cmd/csv2cpe/csv2cpe_test.go
- cvefeed/internal/nvdjson/interfaces.go
- cvefeed/internal/nvdjson/smartvercmp_test.go
- nvdjson.smartVerCmp was comparing the full version strings instead of
major, minor, path etc. substrings;
- off-by-one error in AttributeColumnMap.CPE()
This fixes #18 and #21
> Fix two bugs:

- build_tarballs.sh
- rpm/nvdtools.spec
As required by Facebook FOSS policy.
> add missing copyright notices

- cvefeed/internal/nvdjson/interfaces.go
Restructure if branches to make code more readable, compact commentaries, remove unneccessary variables etc.
> [nvdjson] Some cosmetic on smartVerCmp and relatives.

- README.md
- cmd/flexera2nvd/flexera2nvd.go
- providers/flexera/api/client.go
- providers/flexera/api/http.go
- providers/flexera/converter/converter.go
- providers/flexera/converter/converterutils.go
- providers/flexera/rate/rate.go
- providers/flexera/schema/advisory_details.go
- providers/flexera/schema/advisory_details.json
- providers/flexera/schema/advisory_details_example.json
- providers/flexera/schema/advisory_list.go
- providers/flexera/schema/advisory_list_example.json
Create a tool to download flexera advisories data and convert it to NVD
format
Test:
```
go run ./cmd/flexera2nvd -since 1h >/dev/null
2019/04/26 13:00:32 flexera2nvd.go:77: Download window: Fri, 26 Apr 2019 12:00:32 BST - Fri, 26 Apr 2019 13:00:32 BST
2019/04/26 13:00:34 client.go:57: starting sync for 12 advisories over 1 pages
```
> [provider] flexera2nvd

- cvss3/base_metrics.go
- cvss3/common.go
- cvss3/environmental_metrics.go
- cvss3/score.go
- cvss3/score_test.go
- cvss3/temporal_metrics.go
- cvss3/vector.go
- cvss3/vector_test.go
Improved version of ./cvss/v3
Test: go test
> [cvss3] Use strongly typed enums for cvss3 vector

- cvefeed/nvdjson/interfaces.go
One of the earlier pull requests introduced a performance regression.
The problem was that on each input cpe it was parsing all nodes in the
dictionary to construct wfn.Attributes. This is obviously a wrong
approach since we can parse them in the start and then just match on
input cpes.
This is done in the interfaces.go file using helper structs cpeMatch,
node and cveItem which are just wrappers around corresponding fields in
the NVD jsonchema.
Another "bug" was noticed, and fixed.
When the node had children, it wasn't parsed recursively so some
matching might not work as specified in the feed. Now it's fixed
(recursively calling `newNode()`)
Test: `go build && go test`
Also, tested on our production dataset. Before this commit, it took more
than 4 minutes to process 10 (huge) lines of …
> [cpe2cve] Optimization

- cmd/cpe2cve/cpe2cve.go
-provider and -provider_field flags are used to insert the provider into
the output of cpe2cve.
Test:
```
$ echo 'cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*' | go run ./cmd/cpe2cve -cpe 1 -cve 2 -provider hrenic -provider_field 3 nvd.json
cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*	CVE-1999-0798	hrenic
cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*	CVE-2001-1133	hrenic
...
$ echo 'cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*' | go run ./cmd/cpe2cve -cpe 1 -cve 3 -provider hrenic -provider_field 2 nvd.json
cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*	hrenic	CVE-2008-4609
cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*	hrenic	CVE-1999-0798
...
$ echo 'cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*' | go run ./cmd/cpe2cve -cpe 1 -cve 2 -provider hrenic nvd.json
cpe:2.3:o:bsdi:bsd_os:3.1:*:*:*:*:*:*:*	CVE-1999-0798 …
```
> [cpe2cve] Add provider flag

- cmd/fireeye2nvd/fireeye2nvd.go
- providers/fireeye/api/client.go
- providers/fireeye/api/threat.go
- providers/fireeye/api/vulnerability.go
- providers/fireeye/converter/converter.go
- stats/stats.go
Adds counters to the program for all kinds of stuff.
> [fireeye] Add counters for requests and vulnerabilities

- cmd/rbs2nvd/README.md
- cmd/rbs2nvd/rbs2nvd.go
- providers/lib/download/http.go
- providers/rbs/api/client.go
- providers/rbs/converter/converter.go
- providers/rbs/schema/schema.go
Implemented fetching and converting to NVD for risk based security
> [rbs] Add downloader for new provider

- cmd/idefense2nvd/idefense2nvd.go
- cmd/rbs2nvd/rbs2nvd.go
- providers/idefense/api/client.go
- providers/idefense/schema/convert.go
- providers/idefense/schema/convertutils.go
- providers/lib/runner/config.go
- providers/lib/runner/main.go
- providers/rbs/api/client.go
- providers/rbs/schema/convert.go
This should make all vendor converters behave in the same way and have
the same functionallity.
They already kind of did, just making it official.
If it's good good, I'll change other providers too (except for nvd
itself)
> Create a converter framework

- cmd/idefense2nvd/idefense2nvd.go
- cmd/rbs2nvd/rbs2nvd.go
- providers/idefense/schema/convert.go
- providers/lib/runner/main.go
- providers/rbs/schema/convert.go
Add ID function to convertible so we can have a keyed map instead of an
array
> [provider] Add ID func to Convertible

- cmd/fireeye2nvd/README.md
- cmd/fireeye2nvd/fireeye2nvd.go
- cmd/flexera2nvd/README.md
- cmd/idefense2nvd/README.md
- cmd/snyk2nvd/README.md
- cmd/snyk2nvd/snyk2nvd.go
Also update README.md to reflect latest changes
> [providers][api-keys] Change api key variable names

- cmd/fireeye2nvd/fireeye2nvd.go
- cmd/flexera2nvd/flexera2nvd.go
- cmd/idefense2nvd/idefense2nvd.go
- cmd/snyk2nvd/snyk2nvd.go
> [providers] Make sure that providers fail (exit with !0) when an error

- cpeparse/rpmname.go
- cvefeed/vuln.go
Rewritten the function to parse the epoch as well.
Also, parse it from left to right, instead of right to left.
+ add copyright to cvefeed/vuln.go
Test: go test ./...
> [cpeparse] Add parsing of epoch

- rpm/parse.go
- rpm/parse_test.go
It wasn't parsing rpms with names which had - in them correctly.
> [rpm] Another fix

- cmd/wfnconvert/options.go
- cmd/wfnconvert/process.go
- cmd/wfnconvert/wfnconvert.go
- cmd/wfnconvert/wfnconvert_test.go
> wfnconvert: a tool for manipulating CPEs

- providers/lib/client/client.go
Extract common client functionality (throttling, retries) into a
separate library. It will be used in all providers eventually.
```
go test ./...
```
> [client] Interface for a client

- providers/lib/client/config.go
- providers/lib/client/retry.go
> [client][retries] Exponential backoff and retries of all statuses

- cvefeed/nvd/smartvercmp.go
- cvefeed/nvd/smartvercmp_test.go
before: 1.4 < 1.02; after 1.4 > 1.02.
Added to unittest too.
> Bufgix smartVerCmp

- cvefeed/cvecache.go
Currently, computing the key indexing the CVE cache depends on the order of the
list of CPEs. The cache hit ratio is a good way to evaluate how effective we
are at using the cache.
Sorting the incoming list of CPEs bumps the hit ratio from ~68% to ~95% on a
random sample of 1000 list of CPEs and improves wall runtime by 10%.
> [cvfeed] Provide utility to compute the CVE cache hit ratio

- README.md
and "How build " "download data"
> and "How build " "download data"

- cvss3/score.go
- cvss3/score_test.go
This fixes https://github.com/facebookincubator/nvdtools/issues/190
> update cvss3 base score equation

- rpm/parse.go
- rpm/parse_test.go
This CPE can then later be used for the matching in the RH feed.
> Add function to infer RHEL CPE from a RPM
