facebookincubator/nvdtools

cpeparse/rpmname.go
cpeparse/rpmname_test.go

TL;DR:
```
$ echo "cdp-0.33-3.src.rpm" | rpm2cpe -cpe 2 -rpm 1
cdp-0.33-3.src.rpm      cpe:/a::cdp:0.33:3:~~~~src~
```
should instead be
```
$ echo "cdp-0.33-3.src.rpm" | rpm2cpe -cpe 2 -rpm 1
cdp-0.33-3.src.rpm      cpe:/a::cdp:0.33:3
```
which this patch delivers.

Identify source RPM packages as suitable for any hardware architecture.

---

cvefeed/cvecache.go

namely, unnecessarily exported constant and unneeded else clause

cosmetics: fix 2 linter warnings

---

cmd/nvdsync/datafeed/http.go
cmd/nvdsync/main.go

Test Plan: Used `fmt.Print` to print the UserAgent inside the `httpNewRequestContext` function. `-user_agent` worked as expected, default value is the same as it was before

Enable setting UserAgent from cmdline in nvdsync

---

cmd/nvdsync/datafeed/http.go
cmd/nvdsync/main.go
cmd/rpm2cpe/rpm2cpe_test.go
cpedict/cpedict.go
cpedict/lookup.go
cvefeed/matching_json_test.go
cvefeed/matching_xml_test.go
wfn/wfn.go

format with `gofmt -s`:
* nvdtools/cmd/rpm2cpe/rpm2cpe_test.go
* nvdtools/cmd/rpm2cpe/rpm2cpe_test.go
* nvdtools/cvefeed/matching_xml_test.go
address linter warnings:
* nvdtools/cmd/nvdsync/main.go
* `Line 41: warning: don't use underscores in Go names; var default_ua should be defaultUa (golint)`
* nvdtools/cmd/nvdsync/datafeed/http.go
* `Line 25: warning: exported var UserAgent should have comment or be unexported (golint)`
spelling:
* nvdtools/wfn/wfn.go:75: "beggining" is a misspelling of "beginning"
* nvdtools/cmd/rpm2cpe/rpm2cpe_test.go:81: "succeded" is a misspelling of "succeeded"
* nvdtools/cpedict/cpedict.go:113: "occurances" is a misspelling of "occurrences"
* nvdtools/cpedict/lookup.go:52: "wich" is a misspelling of "which"

Cosmetics/linter:

---

.travis.yml
Makefile
build_tarballs.sh

Since we want to dynamically create releases based on the git commit tags, we should reuse the tagging provided by travis.

Adding versioning based on tags

---

cvefeed/internal/nvdjson/interfaces.go
cvefeed/internal/nvdjson/smartvercmp_test.go
cvefeed/matching_json_test.go

It was compairing the version strings lexicographically, without any account of
versioning schemes (e.g. semver). Thus, version `16.0.0` was recognized as a smaller version than `3.0.0`:
```
dvl-mbp:cvefeed dvl$ go test -run smartVersion
--- FAIL: TestMatchJSONsmartVersionMatching (0.00s)
matching_json_test.go:111: version 52\.0 matched, albeit it should not
FAIL
exit status 1
FAIL    github.com/facebookincubator/nvdtools/cvefeed   0.026s
```
This patch replaces relevant strings.Compare() calls with calls to a custom func smartVerCmp().
The latter splits the version on dots and processes each part separately.
It compares numerical suffixes at the beginning of each part as numbers and the rest lexicographically:
```
dvl-mbp:nvdjson dvl$ go test -v
=== RUN   TestSmartVerCmp
=== RUN …
```

Range matching for versions was performed wrong in nvdjson.MatchPlatform.

---

.travis.yml
Makefile
build_tarballs.sh
debian/rules
rpm/Makefile

Current releases had `v` in all the files which is against a current standard.
Therefore, we should remove this.
Example versioning: ![image](https://user-images.githubusercontent.com/17247404/51634663-bcfa3300-1f4c-11e9-90c6-eba5f666c8cc.png)

Fixing versioning of releases to get rid of `v` in files

---

cvefeed/internal/nvdjson/interfaces.go
cvefeed/internal/nvdjson/smartvercmp_test.go

I figured, there was no need to actually parse the numbers from the strings. These are integers with no leading zeros, hence the longer one is the larger and if the length is equal, then lexicographical comparison does the right thing.
Benchmarks (BenchmarkSmartVerCmp is the new version and BenchmarkSmartVerCmp2 is the old one):
```
$ go test -bench .
goos: linux
goarch: amd64
pkg: github.com/facebookincubator/nvdtools/cvefeed/internal/nvdjson
BenchmarkSmartVerCmp-8          20000000                99.9 ns/op
BenchmarkSmartVerCmp2-8         10000000               206 ns/op
PASS
```

Improve the performance of smartVerCmp function.

---

cvefeed/internal/nvdjson/interfaces.go
cvefeed/internal/nvdjson/smartvercmp_test.go
cvefeed/matching_json_test.go

The check for character being a digit was broken. Everything boils down to this:
```
-               if v[skip] < 0 || v[skip] > '9' {
+               if v[skip] < '0' || v[skip] > '9' {
```

Fix smartVerCmp (again).

---

cmd/cpe2cve/cpe2cve.go
cmd/cpe2cve/cpe2cve_test.go
cmd/cpe2cve/fieldstoskip.go
cmd/cpe2cve/fieldstoskip_test.go
cmd/cpe2cve/multistring.go
cvefeed/cvecache.go
cvefeed/dictionary.go
cvefeed/eviction_test.go
cvefeed/internal/iface/iface.go
cvefeed/matching_overrides_test.go

E.g.:
```
cat ./inventory.csv | cpe2cve -feed json -cpe 1 -cve 2 -r ./override1.json -r ./override2.json ./feed.json
```
This resolves #9.
As a collateral damage this also resolves #23 (I was bored, I guess).

[cmd/cpe2cve] Introduce feeds overrides.

---

cvefeed/cvecache.go

There is no point in crashing the whole binary on that, printing a warning and discarding the entry should be sufficient.

cvecache: replace the panic when an element of the cpe list is nil by a warning

---

cmd/cpe2cve/cpe2cve.go
cmd/cpe2cve/fieldstoskip.go
cvefeed/cvecache.go
cvefeed/eviction_test.go
cvefeed/internal/iface/iface.go
cvefeed/internal/nvdjson/interfaces.go
cvefeed/internal/nvdxml/interfaces.go
cvefeed/internal/nvdxml/schema.go

CVSS base score and CWE allow us to evaluate the severity of vulnerabilities we find.
Ideally cpe2cve should be able to output any information about vulnerability, granted that informatino is in the feed.
That's a start, we can add more later.
This solves #24.
SOZ, no unittests, #movefast:
```
$ echo cpe:/o:juniper:junos:12.1x46 | ./cpe2cve -cpe 1 -cve 2 -cwe 3 -cvss 4 -cvss2 5 -cvss3 6 ~/feeds/xml/nvdcve-2.0-2018.xml.gz
cpe:/o:juniper:junos:12.1x46    CVE-2018-0019           4.3     4.3     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0001           7.5     7.5     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0017           6.8     6.8     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0031           4.3     4.3     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0003           6.1     6.1 …
```

[cpe2cve] new feature: output CVSS base score and CWE.

---

cvefeed/internal/nvdxml/interfaces.go

:[
```
$ echo cpe:/o:juniper:junos:12.1x46 | ./cpe2cve -cpe 1 -cve 2 -cwe 3 -cvss 4 -cvss2 5 -cvss3 6 ~/feeds/xml/nvdcve-2.0-2018.xml.gz
cpe:/o:juniper:junos:12.1x46    CVE-2018-0004   CWE-400 7.1     7.1     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0019   CWE-20  4.3     4.3     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0051   CWE-20  4.3     4.3     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0049   CWE-476 7.1     7.1     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0060   CWE-20  4.3     4.3     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0017   CWE-20  6.8     6.8     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0061   CWE-400 5.0     5.0     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0022   CWE-400 7.8     7.8     0.0
cpe:/o:juniper:junos:12.1x46    CVE-2018-0003 …
```

[cpe2cve] forgot to implement CVEItem.ProblemTypes() func for XML feed

---

wfn/fsb.go
wfn/wfn.go
wfn/wfn_test.go

The docstring says:
```
Quoted wildcards (*?) become unquoted ones (i.e. act as wildcards, not a literal '*' and '?')
```
yet the function completely disregrads '*' and '?' characters and just drops them from the output.
This makes it behave as described (also see additional test cases in wfn_test.go).

[wfn] Make WFNize() behaviour consistent with function documentation.

---

cvefeed/internal/nvdjson/interfaces.go
cvefeed/internal/nvdjson/smartvercmp_test.go

Versioning is hard, version relations are even harder. Kerberos, for instance,
has versions like 5-1.15.2 and  5_1.0.6. I did my best to account for stuff like
this in this PR.

smartVerCmp: all punctuation chars are separators, don't compare them.

---

cvefeed/dictionary.go
cvefeed/internal/nvdjson/interfaces.go
cvefeed/internal/nvdjson/nvdjson.go
cvefeed/matching_json_test.go

We have ran into an issue, when our feed had a malformed item, which led to a processor crash. Reproducable like this:
```
$ cat ~/stuff/feed.json
{"CVE_data_format":"","CVE_data_type":"","CVE_data_version":"","CVE_Items":[{"cve":null}]}
$ echo "cpe:/a:product:version" | ./cpe2cve --feed=json -cpe=1 -cve=2 ~/stuff/feed.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10f5571]
goroutine 6 [running]:
github.com/facebookincubator/nvdtools/cvefeed/internal/nvdjson.reparse(0xc4200b2070, 0x1126760, 0xc4200b2070, 0x0, 0x0, 0x113cf40)
/Users/dvl/go/src/github.com/facebookincubator/nvdtools/cvefeed/internal/nvdjson/nvdjson.go:44 +0x241
github.com/facebookincubator/nvdtools/cvefeed/internal/nvdjson.Parse(0x17 …
```

Be a bit more defensive when parsing JSON feed.

---

cvefeed/internal/nvdjson/interfaces.go

Accordingly to CPE spec version=N/A matches version=Any.
When we have version ranges in our feed, the version of CPE is usually set to Any to allow range match.
But version=N/A should not match any range, yet now it might. This fixes it.

Don't match version of logical value N/A against version ranges.

---

cmd/cpe2cve/cpe2cve.go

Summary:
It was a simple change. Instead of calling unbindPrefix directly, just call parse which will try to parse it first as cpe 2.2 and then 2.3
Test Plan:
→ echo 'cpe:2.3:a:*:k8s.io/kubernetes:*:*:*:*:*:*:*:*' | go run ./cmd/cpe2cve  -nproc 24 -idxd -cpe 1 -cve 1 -e 1 -feed json $f
SNYK-GOLANG-K8SIOKUBERNETES-50026
SNYK-GOLANG-K8SIOKUBERNETES-50004
SNYK-GOLANG-K8SIOKUBERNETES-50019

Cpe2.3 support for cpe2cve

---

.travis.yml
README.md
cmd/rustsec2nvd/rustsec2nvd.go
cvefeed/nvdcommon/nvdcommon.go
providers/rustsec/rustsec.go
providers/rustsec/rustsec_test.go

Converter for RustSec TOML advisories to NVD CVE JSON 1.0 feed format.
Besides the unit test for the converter, also tested the generated file
with cpe2cve.
Cloned the repo, generated the NVD CVE JSON feed:
```
git clone https://github.com/RustSec/advisory-db
go run rustsec2nvd.go ./advisory-db/crates/ > rustsec.cve.json
```
Picked a random advisory for testing, e.g. https://github.com/RustSec/advisory-db/blob/master/crates/cookie/RUSTSEC-2017-0005.toml
Checked non-match boundaries:
```
$ echo cpe:/a::cookie:0.5.9 | cpe2cve -require_version -cpe=1 -cve=2 -feed=json rustsec.cve.json
$ echo cpe:/a::cookie:0.6.2 | cpe2cve -require_version -cpe=1 -cve=2 -feed=json rustsec.cve.json
$ echo cpe:/a::cookie:0.7.6 | cpe2cve -require_version -cpe=1 -cve=2 -feed=json rustsec.cve.json
```
Checked …

Add rustsec2nvd converter

---

README.md
cmd/fireeye2nvd/fireeye2nvd.go
providers/fireeye/api/client.go
providers/fireeye/api/parameters.go
providers/fireeye/api/threat.go
providers/fireeye/api/vulnerability.go
providers/fireeye/converter/converter.go
providers/fireeye/converter/converterutils.go
providers/fireeye/schema/error.go
providers/fireeye/schema/report.go
providers/fireeye/schema/result.go
providers/fireeye/schema/vulnerability.go

Summary:
This diff adds the ability to fetch fireeye data and convert it into NVD format.
Test Plan:
```
$ with_proxy go run ./cmd/fireeye2nvd -since 1h >/dev/null
2019/04/26 03:17:00 fireeye2nvd.go:70: Downloading since Fri, 26 Apr 2019 02:17:00 PDT
2019/04/26 03:17:00 vulnerability.go:19: Fetching: Start: (Fri, 26 Apr 2019 02:17:00 PDT); End: (Fri, 26 Apr 2019 03:17:00 PDT)
2019/04/26 03:17:01 vulnerability.go:24: Adding 16 vulns
$ echo $?
0
```

[provider] Add fireeye provider

---

Makefile
cmd/fireeye2nvd/fireeye2nvd.go
cmd/flexera2nvd/flexera2nvd.go
cmd/idefense2nvd/idefense2nvd.go
providers/idefense/schema/script.sed

we don't need this open sourced. Lets just drop it and download all
data, user can still set the boundary with -since_unix or -since flags
also, add idefense2nvd to Makefile

[provider] Remove startOfTImes from providers

---

providers/fireeye/api/client.go
providers/fireeye/api/threat.go
providers/fireeye/api/vulnerability.go

Summary:
When running multiple goroutines, sha256 internal package panics. I've
debugged this and the problem was that multiple goroutines we're messing
with the same hash.Hash object.
Fixed it by adding a lock to this function
Test:
Fireeye2nvd still works

[provider][fireeye] Make client goroutine safe

---

cvss/common/metrics.go
cvss/common/metrics_test.go
cvss/v3/score.go
cvss/v3/score_test.go
cvss/v3/vector.go
cvss/v3/vector_test.go
cvss/vector.go

This commit implements a simple library for handling cvssv3 vectors and
calculating it's score. It was made as generic as possible so that it
would be easy to implement cvssv2 reusing most of the components.
[Test]
go test -v ./...

[CVSS] Implementation of the CVSSv3 vector

---

cmd/cpe2cve/cpe2cve.go

We've killed of xml feed as part of #45, so there's no need for the feed
flag anymore.
Test: go test ./... && go build ./...

[cpe2cve] remove -feed flag

---

cvss/common/metrics.go
cvss/common/metrics_test.go
cvss/v2/score.go
cvss/v2/vector.go
cvss/v3/score.go
cvss/v3/vector.go

This diff enables us to parse undefined values. But it ignores them
(doesn't call `Set` if the parsed value is undefined). Also, doesn't print
undefined values in `String()`
So if we have a cvss v3 vector `v` set to `E:U`, calling
`v.Parse("E:X/RL:X/RC:C").String()` will produce `"E:U/RC:C"`
Also, made weights easier to use by removing weights default.
```
$ (go build ./... && go test ./...) >/dev/null && echo good good
good good
```

[cvss] Enable parsing of undefined values

---

cvss3/score.go
cvss3/score_test.go
cvss3/temporal_metrics.go
cvss3/vector.go
cvss3/vector_test.go

calling v1.parse(str) could fail in the middle so some of the values
would change and some wouldn't. There would be no way to recover.
This way we separate this into first parsing the vectors on each own and
then doing merge (absorb or absorbDefined)
Absorb will absorb only the values in the new vector which are
actually defined and override them in the first vector.

[cvss3] Better API for cvss3 vector

---

stats/stats.go
stats/stats_test.go

This library will be used through most (all) of our tools to count
success/error API calls, speed of processing, ....
Test: go test -v ./stats
Real test:
- create file `./cmd/hrenic/hrenic.go` :
```
package main
import (
"flag"
"github.com/facebookincubator/nvdtools/stats"
)
func main() {
stats.Global.AddFlags()
flag.Parse()
stats.Global.IncrementCounter("hrenic")
stats.Global.Write()
}
```
```
$ go run ./cmd/hrenic -h
Usage of /var/folders/ts/x_kfp_tn4md6wzskj_4vlwpxb7n_9t/T/go-build793734886/b001/exe/hrenic:
-log_stats
log stats to stderr
-output_stats string
output stats to this file
-stats_encoding string
how to encode stats, either csv or json (default "csv")
exit status 2
$ go run ./cmd/hrenic -log_stats
hrenic,1
$ go run ./cmd/hrenic -log_stats -output_stats=file.csv
hrenic,1
$ cat …
```

[stats] Create a library for updating counters

---

cmd/cpe2cve/cpe2cve.go

When there's a cpe which cannot be parsed, there's a panic in the
matching phase.
Before fix:
```
$ echo asdf | go run ./cmd/cpe2cve -cpe 1 -cve 2 ~/dev/snyk_golang.json
E0704 10:53:24.927330   33013 cpe2cve.go:128] couldn't parse uri "asdf": wfn: unsupported format "asdf"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1105194]
goroutine 52 [running]:
github.com/facebookincubator/nvdtools/cvefeed/nvdjson.(*node).MatchPlatform(0xc000311d10, 0x0, 0x0, 0x0)
/Users/hrenic/Projects/gopath/src/github.com/facebookincubator/nvdtools/cvefeed/nvdjson/interfaces.go:130 +0x34
github.com/facebookincubator/nvdtools/cvefeed.matchLogicalTest(0xc00022d6b0, 0xc0000baa60, 0x1, 0x1, 0x118de00, 0xc000311d10, 0x1136f00, …
```

[cpe2cve] Resolve a panic in cpe2cve

---

providers/lib/runner/config.go
vulndb/summary.go
vulndb/time.go

Now summary also shows the latest modified and published dates stored in
vulndb.
Also, make vulndb.TimeLayout map to nvdcommon.TimeLayout (since they are
the same)
Also, make providers -since flag parse this layout, for consistency.
Test: go build ./...
Also tested `vulndb summary` locally, but data redacted so we don't show
the used vendors/data.

[vulndb] Add modified and published date to summary

---

cmd/cpe2cve/cpe2cve.go
stats/stats.go

Track run time, load dictionary time, process time
Also track the total number of lines/cpes and number of matched
lines/cpes
```
→ echo asdf | go run ./cmd/cpe2cve -cpe 1 -cve 2 -log_stats ~/dev/nvd.json
E0715 15:30:38.971611    5523 cpe2cve.go:138] couldn't parse uri "asdf": wfn: unsupported format "asdf"
line.total,1
cpe.total,1
cpe.error,1
dictionary.load,13.00
process.time,0.00
run.time,13.00
```

[cpe2cve] Add stats to cpe2cve

---

providers/flexera/api/client.go
providers/idefense/api/client.go
providers/rbs/api/client.go

We want the -since flag to query the APIs and return a list of all vulns
which were modified (not published/released) since then.

[providers] Make sure all providers fetch since last modification

---

cmd/cpe2cve/config.go
cmd/cpe2cve/cpe2cve.go
cmd/cpe2cve/cpe2cve_test.go
cmd/cpe2cve/fieldstoskip.go

This commit adds support for using multiple feeds in cpe2cve and having
their names in output.
When you do `./cpe2cve -v=1 -h`, it shows how the config file should be
formatted:
```
Config file definition [JSON]:
{
"CPEsAt": 0,
"CVEsAt": 0,
"MatchesAt": 0,
"CWEsAt": 0,
"CVSS2At": 0,
"CVSS3At": 0,
"CVSSAt": 0,
"EraseFields": [],
"ProviderAt": 0,
"InFieldSeparator": "",
"InRecordSeparator": "",
"OutFieldSeparator": "",
"OutRecordSeparator": "",
"NumProcessors": 0,
"IndexDict": false,
"CacheSize": 0,
"RequireVersion": false,
"CPUProfile": "",
"MemoryProfile": "",
"FeedOverrides": [
"override feed path"
],
"Feeds": {
"provider": "feed file path"
}
}
```
Example:
```
$ echo "cpe:2.3:a:*:k8s.io\\/kubernetes:*:*:*:*:*:*:*:*" | go run ./cmd/cpe2cve -cpe 1 -cve 2 -provider_field 3 …
```

[cpe2cve] Add support for multiple named feeds; config file

---

cmd/cpe2cve/cpe2cve_test.go
cmd/csv2cpe/csv2cpe.go
cmd/csv2cpe/csv2cpe_test.go
cmd/rpm2cpe/rpm2cpe.go
cmd/rpm2cpe/rpm2cpe_test.go
cpeparse/rpmname.go
cpeparse/rpmname_test.go
wfn/uri.go
wfn/wfn.go

wfn.Any happends to be "", which is zero-value for a string.
We rely on this all over the place, including in csv2cpe and rpm2cpe tools,
which is not correct in the latter cases, it should be wfn.NA instead.

Non-existent wfn attributes default to wfn.NA instead of wfn.Any.

---

vulndb/schema.sql
vulndb/vendor.go

When we insert stuff into vendor_data, sometimes a batch can be to big
and won't insert. So instead, we just subdivide the batches into smaller
portions (until a batch size is 1) and try to insert those.
go test ./... works. Tested insert, works
also, move batch size from 10 to 100.

[vulndb] Subdivide batches when inserting fails

---

cvefeed/nvd/match_cpe.go

Vulnerable flag in cpe match means whether or not the product in
configuration is vulnerable to some cve. It's not the same as Negate
operator.
go test ./...
ran cpe2cve with previously false positive input, not outputed anymore

[cpe2cve] Matching fix

---

cmd/cpe2cve/cpe2cve.go
cmd/nvdsync/main.go
cmd/rustsec2nvd/rustsec2nvd.go
cvefeed/cvecache.go
providers/nvd/cve.go

it wasn't previously added so some binaries lost their -v flag (cpe2cve)
go test ./... go build ./...

[flog] Add flog.AddFlags to init

---

cmd/csv2cpe/csv2cpe.go
cmd/csv2cpe/csv2cpe_test.go
cmd/rpm2cpe/rpm2cpe.go
cmd/rpm2cpe/rpm2cpe_test.go

Basically, add an `-na` option to both rpm2cpe and csv2cpe tools;
when set, the default value is N/A; otherwise they stick to ANY.

Make default attribute value for CPE generation configurable.

---

rpm/parse.go
rpm/parse_test.go
rpm/rpm2wfn_test.go

It was being parsed in a wrong way. We need to strip name and arch first
and then parse the label which has optional parts
go test ./...

[rpm] Fix parsing of packages

---

rpm/checker.go

The goal of this interface is to answer the question: is some package
fixed for the given CVE on some distribution.
Next diffs will implement this checker for the redhat feed.

[rpm] Create rpm checker interface

---

cmd/redhat2nvd/redhat2nvd.go
providers/lib/client/client.go
providers/redhat/api/client.go
providers/redhat/schema/convert.go
providers/redhat/schema/convertutils.go
providers/redhat/schema/schema.go

This diff adds the publicly available RedHat feed as one possible
provider.
Test:
Using the already built tool, I ran this
```
go run ./cmd/redhat2nvd -download -since 24h > redhat.json
go run ./cmd/redhat2nvd -convert < redhat.json > nvd.json
```
redhat.json:	https://pastebin.com/hh9JHvs2
nvd.json:	https://pastebin.com/uRCvTSpa

Add RedHat feed to the providers

---

providers/lib/client/client.go
providers/lib/client/config.go
providers/lib/client/execute.go
providers/lib/client/retry.go
providers/lib/client/throttle.go

So it's easier to follow, file was getting to big.
Each "modifier" (throttle, retries...) in its own file
Simplify usage and avoid code repetition by introducing the executor
Client
go test ./...
go run redhat2nvd ...

[lib] Refactor client into separate files

---

cmd/redhat_filter/main.go
cmd/redhat_filter/main_test.go
providers/redhat/check/check_cve.go
providers/redhat/check/check_cve_test.go
providers/redhat/check/check_pkg.go
providers/redhat/check/check_pkg_test.go
providers/redhat/feed.go
providers/redhat/schema/convert.go
providers/redhat/schema/convertutils.go
rpm/checker.go
rpm/checker_test.go

RedHat feed
RedHat feed tells us which rpm packages have been fixed for which
release for which CVE.
This binary implements this kind of filtering.
Input is in csv format and you specify which fields contain packages,
distribution and cve. Output is the same format as input, just has
packges filtered out. Only the ones that haven't been reported as fixed
stay in the output.
go test ./...

[redhat] Implement a binary to filter out fixed packages based on the

---

providers/redhat/check/check_cve.go
providers/redhat/check/check_pkg.go
providers/redhat/schema/convertutils.go
rpm/checker_test.go

- add license header to rpm/checker_test.go
- add malformed package to the filter test
- switch TODO for XXX
- un-embed the pkgCheck from the singleChecker
- redhat: under investigation -> not fixed
Test: `go test ./...`

[rpm/redhat] Minor fixes from the previous pull request

---

providers/nvd/cve.go

This pull requests adds support to nvdsync to download vulnerability
database in the newest NVD JSON 1.1 schema.
https://nvd.nist.gov/General/News/JSON-1-1-Vulnerability-Feed-Release
This should resolve #116 
Test: https://pastebin.com/raw/2KhKUTJu

[nvd] Add support to nvdsync for JSON 1.1 schema

---

cvss3/score.go
cvss3/score_test.go
cvss3/vector.go
cvss3/vector_test.go

https://www.first.org/cvss/user-guide
This pull requests add support for CVSS version 3.1
The formula to calculate modified impact sub-score was changed, and it
can be seen in the code as well.
Added tests for new changes.

[cvss3] Add support for new version of CVSS3 (3.1)

---

cvss3/environmental_metrics.go
cvss3/score.go
cvss3/score_test.go
cvss3/vector.go
cvss3/vector_test.go

In the Common Vulnerability Scoring System v3.1: Specification Document, Environmental Score is defined by a formula which depends on *Modified* Base Metrics, Temporal Metrics and 3 other ones: ConfidentialityRequirement, IntegrityRequirement and AvailabilityRequirement.
**This PR allows for Temporal Metrics to also be Modified so that, if they are, its value would override the Temporal Metric one while calculating the Environmental Score**.
So, instead of something like 
```
EnvironmentalScore = Roundup ( Roundup [Minimum ([ModifiedImpact + ModifiedExploitability], 10) ] × ExploitCodeMaturity × RemediationLevel × ReportConfidence)
```
We would have
```
EnvironmentalScore = Roundup ( Roundup [Minimum ([ModifiedImpact + ModifiedExploitability], 10) ] × ModifiedExploitCodeMaturity × …
```

Extend CVSS3 specification: Modified Temporal metrics

---

cvss2/environmental_metrics.go
cvss2/score.go
cvss2/score_test.go
cvss2/vector.go
cvss2/vector_test.go

In the Common Vulnerability Scoring System v2: Specification Document, Environmental Score is defined by a formula which depends on General Modifiers, Temporal Metrics and Impact Subscore Modifiers.
This PR allows for Temporal Metrics to also be Modified so that, if they are, its value would override the Temporal Metric one while calculating the Environmental Score.

Extend CVSS2 specification: Modified Temporal metrics

---

.travis.yml
README.md
cmd/fireeye2nvd/fireeye2nvd.go
cmd/flexera2nvd/flexera2nvd.go
cmd/idefense2nvd/idefense2nvd.go
cmd/rbs2nvd/rbs2nvd.go
cmd/redhat2nvd/redhat2nvd.go
cmd/snyk2nvd/snyk2nvd.go
providers/fireeye/api/client.go
providers/fireeye/api/threat.go
providers/fireeye/api/vulnerability.go
providers/flexera/api/client.go
providers/idefense/api/client.go
providers/lib/client/client.go
providers/lib/client/debug.go
providers/lib/runner/main.go
providers/snyk/api/client.go

This PR enables clean cancellation of pending HTTP requests in 3 providers:
- Propagates a `context.Context` from the `Runner` to `client.Get`
- Modify the concurrent HTTP fetching code in idefense, fireeye and flexera to use errgroup
- BONUS! I've added an HTTP request tracer that was handy to debug what the tools were doing. Users of the client package will automatically inherit this capability, another good reason to push for all tools to use the client package.
```
Req 1: GET /api/advisories?modified__gte=1579615394&modified__lt=1579622594&page_size=1          HTTP/1.1
Host: api.app.secunia.com
Authorization: Token xxx
Req 1: HTTP/1.1 200 OK
2020/01/21 16:03:15 client.go:71: starting sync for 4 advisories over 1 pages
Req 2: GET …
```

Propagate a context.Context and use errgroups to cancel pending HTTP GETs on error

---

providers/lib/client/debug.go

The http failure injection code uses the request number to decide if it should
fail a request or not. Request numbers start at 1. 0 is never assigned as a
request number and 0 is used to mean "no fault injection".
Unfortunatly, traceRequestStart was returning 0 when tracing was disabled,
which meant that, under normal usage, all requests were triggering the fault
injection code. Argh!

client: Always return a valid request id even if tracing is disabled

---

cmd/redhat2nvd/redhat2nvd.go
providers/redhat/api/client.go

This PR propagates a context in the redhat provider and uses the new context-aware client.Get() code path.

Use a context.Context for GET requests

---

providers/redhat/schema/schema.go

Checked it was the only instance with:
$ git grep -e '`json:".*[^"]`'

[redhat] Fix missing " in json tag

---

.travis.yml
cmd/cpe2cve/config.go
cmd/rbs2nvd/rbs2nvd.go
providers/redhat/api/client.go
providers/redhat/schema/schema.go
rpm/rpm2wfn.go

Nothing too major found:
- Errors weren't propagated in `rpm.ToWFN`
- Some misspelled json struct tags
- Some unused fields
I've disabled a few default linting passes, more notably `errcheck`: there are many code path where we don't check and propagate errors. This will have to be a task for another time.

Enable some static checking with golangci-lint and fixes a few problems found by the tool

---

providers/redhat/schema/convertutils.go
providers/redhat/schema/convertutils_test.go

The upstream feed must have changed recently, adding the Z at the end of the
time string. We had a wall of:
```
$ redhat2nvd -download -convert -since 240h > redhat-nvd.json
[...]
2020/01/28 11:23:23 convertutils.go:41: unable to parse time: parsing time "2020-01-22T00:00:00Z": extra text: Z
2020/01/28 11:23:23 main.go:162: error while converting vuln: unable to convert published date: parsing time "2020-01-22T00:00:00Z": extra text: Z
```
This error was preventing CVE entries from being converted and those entries
weren't present in the final NVD feed.

[redhat] Fix parsing of time with time zone indicator

---

cmd/redhat_query/fixed-cves.go
cmd/redhat_query/main.go
providers/redhat/feed.go
providers/redhat/package_feed.go
providers/redhat/package_feed_test.go
providers/redhat/schema/schema.go
rpm/checker.go
rpm/compare.go
rpm/compare_test.go
rpm/parse.go
rpm/rpm2wfn.go

We'd like to annotate packages queried through `rpm -qa` or `dnf repoquery` with the list CVEs that aren't applicable to that package, either because the version packaged isn't impacted or because a fix has been pack ported.
We re-use the `rpm.Checker` interface already in place but with a twist.
- The `rpm.Checker` interface answers the question: "for the combination (distro, package, cve), is the CVE fixed?"
- What we want is "for each (distro, package) tuple, give me the list of non applicable/fixed CVEs.
To answer that question we start by turning the feed of CVEs retrieved fro RedHat inside out: we want a map that for each package name gives us the list of CVEs that potentially affect the package. We then use the `rpm.Checker` interface on each (distro, package, cve).
I've also …

[redhat] Add the ability to list non applicable CVEs for a given package

---

providers/redhat/schema/convertutils.go

If we ever encounter an unknown CVE status string, we were answering that the
problem was fixed. Better err on the side of caution and flag the CVE as not
fixed.
We don't want to have a hard parsing error that would stop the whole process,
just surface a warning to be picked up an fixed.

[redhat] Err on the side of caution when facing unknown resolution

---

cmd/redhat_query/fixed-cves.go
providers/redhat/feed.go
providers/redhat/package_feed.go

Turns out I overlooked that we were iterating through the whole Feed to produce
the rpm.Checker. We can cache it.
This makes calling ListFixedCVEs for ~50,000 packages go from 2 minutes to < 1s.
We also don't need to parse the distro string everytime.

[redhat] Make ListFixedCVEs a lot faster when used with many packages

---

providers/redhat/package_feed.go

I like to have a stable output between two invocations of tools for easier
comparison later on. The code producing the list of fixed CVEs loops though a
map, which isn't deterministic in go.
Sorting that list before handing it back to the user helps with that!

[redhat] Sort the list of fixed CVEs

---

.travis.yml

raw.githubusercontent.com/golangci/golangci-lint/master/install.sh script
uses the latest tag by default at the time of commit it is v1.24.0.
This should fix the build failures we've been having lately with v1.23.1

Use latest golangci-lint.

---

wfn/matching.go
wfn/matching_test.go

During my recent profiling of real-world data, I've noticed, that
cpe2cve tool spends about 37% of its time in wfn.HasWildcard.
At this volume any win matters, so I've optimised it a little bit.
Benchmarsk with Old suffix are for the old code, those without it
were ran against the new code.
```
$ go test -bench HasWildcard
goos: linux
goarch: amd64
pkg: github.com/facebookincubator/nvdtools/wfn
BenchmarkHasWildcard/has-4              74283427   16.2 ns/op
BenchmarkHasWildcard/has_not-4          32665263   32.0 ns/op
BenchmarkHasWildcard/has_escaped-4      45591032   26.2 ns/op
BenchmarkHasWildcardOld/has-4           66978981   17.5 ns/op
BenchmarkHasWildcardOld/has_not-4       30594387   38.2 ns/op
BenchmarkHasWildcardOld/has_escaped-4   36729177   27.6 ns/op
PASS
ok …
```

Optimize wfn.HasWildcard a bit.

---

cvefeed/cvecache.go

We've established that sorting the CPEs lead to more cache hits (68% -> 95%).
Instead of having to do it in the client code and have that constraint in the
API, we can sort the CPEs when computing the cache key!
With this and a test 1000 unsorted lists of CPEs, we stay at 95% hit rate.

[cvefeed] Sort CPEs when computing the cache key

---

providers/lib/client/debug.go

This PR improves a debugging facility when downloading vulnerability feeds. 
We can trace HTTP requests when downloading data from providers. At the moment we only trace requests/responses and their headers. This adds the ability to also trace HTTP bodies.

Add ability to dump bodies of HTTP requests and responses

---

cvefeed/matching_json_test.go
cvefeed/nvd/match_cpe.go
wfn/matcher.go

The matching logic did not account for version=ANY in wfn.Attributes
received as an argument.
I added some cases to TestMatchJSON() to reproduce, rule#1 was failing
before the fix.

Fix a bug in cpeMatch.match()

---

cmd/redhat_query/fetch-cve.go
providers/redhat/api/client.go

I needed to check if CVE information hadn't been updated for a particular CVE.
This little utility does just that.
```
$ redhat_query fetch-cve CVE-2013-1961
{
"name": "CVE-2013-1961",
"threat_severity": "Low",
"public_date": "2013-05-02T00:00:00Z",
"bugzilla": {
"description": "CVE-2013-1961 libtiff (tiff2pdf): Stack-based buffer overflow with malformed image-length and resolution",
"id": "952131",
"url": "https://bugzilla.redhat.com/show_bug.cgi?id=952131"
},
"CVSS": {
"cvss_base_score": "4.3",
"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
"status": "verified"
},
"cwe": "CWE-121",
"details": [
"Stack-based buffer overflow in the t2p_write_pdf_page function in tiff2pdf in libtiff before 4.0.3 allows remote attackers to cause a denial of service (application crash) via a crafted …
```

[redhat_query] Add a command to fetch a single CVE from RedHat

---

providers/redhat/schema/schema.go

Turns out we were never unmarshalling data with a mitigation field because it's
not a string but an object with a couple of fields:
```
[...]
"mitigation": {
"value": "This flaw is in the memcached binary protocol. If your client programs only use the ASCII protocol when communicating with memcached, you can disable the binary protocol and protect against this flaw by adding \"-B ascii\" to OPTIONS in /etc/sysconfig/memcached.",
"lang": "en:us"
}
[...]
```
This means we were skipping all CVE entries with a mitigation field in redhat2nvd 😱!
I looked at historical data and that field isn't present in the CVEs with do
have so it was probably never a string!
Before:
```
$ redhat_query fetch-cve CVE-2016-8705
failed to decode cve response into a cve: json: cannot unmarshal object into Go …
```

[redhat] Fix unmarshalling of the mitigation field

---

cmd/vulndb/exportcmd.go

--format nvdcvejson is the correct invocation, not nvdjson!

[vulndb] Fix the help text with the correct format parameter

---

cvefeed/feed.go

We can decode plain and gzip compressed json files. Add support for bzip2
compressed files as well.
Tested it by giving a .bz2 file as input to cpe2cve.

[cvefeed] Support bzip2 compressed feeds

---

cmd/vulndb/diffcmd.go
cvefeed/dictionary.go
cvefeed/diff.go
cvefeed/nvd/match_cve.go

This is the first version of a `diff` command that takes two JSON files from `vulndb export` and compute both status and a set of differences between two prodivers.
```
$ vulndb diff ~/data/nvd.json ~/data/vfeed.json
2020/06/22 17:25:30 diffcmd.go:35: loading /Users/dlespiau/data/nvd.json
2020/06/22 17:25:41 diffcmd.go:35: loading /Users/dlespiau/data/vfeed.json
2020/06/22 17:25:51 diffcmd.go:87: computing stats
Num vulnerabilities in nvd: 145376
Num vulnerabilities in vfeed: 137392
Num vulnerabilities in nvd but not in vfeed: 7984
CVE-1999-0020
CVE-1999-0110
CVE-1999-0187
CVE-1999-0282
CVE-1999-0531
CVE-1999-0614
CVE-1999-0615
CVE-1999-0616
CVE-1999-0617
CVE-1999-0619
... (7974 more)
Num vulnerabilities in vfeed but not in nvd: 0
Different vulnerabilities: 112
different descriptions: 112 …
```

vulndb diff

---

cmd/flexera2nvd/flexera2nvd.go

When running `go run ./cmd/flexera2nvd -download -since 2020-08-31T00:00Z` you need to specify `FLEXERA_TOKEN`.
The `FLEXERA_TOKEN` is in the format `Token <actual token>` but setting `FLEXERA_TOKEN="Token <token>"` is a bit counterintuitive so this PR allows passing only the token itself as in `FLEXERA_TOKEN=<token>` and the "Token " part will be prepended if needed.
Tested by manually running the `go run ...` and setting `FLEXERA_TOKEN="Token <token>"` and `FLEXERA_TOKEN="<token>"` and both work.

Allow passing `FLEXERA_TOKEN` env variable without prefixing with "Token"

---

cmd/vulndb/customcmd.go
cmd/vulndb/diffcmd.go
cmd/vulndb/editcmd.go
cmd/vulndb/exportcmd.go
cmd/vulndb/main.go
cmd/vulndb/snoozecmd.go
cmd/vulndb/summarycmd.go
cmd/vulndb/vendorcmd.go

Changing vulndb's `log` calls with `flog` is the first step towards unifying all our log messages to GLOG format. This will bring consistency to our logs since some utilities use `flog` and others use `log`

Replacing vulndb `log` calls with flog to output log messages in GLOG format

---

cmd/csv2cpe/csv2cpe.go
cmd/fireeye2nvd/fireeye2nvd.go
cmd/flexera2nvd/flexera2nvd.go
cmd/idefense2nvd/idefense2nvd.go
cmd/rbs2nvd/rbs2nvd.go
cmd/redhat2nvd/redhat2nvd.go
cmd/snyk2nvd/snyk2nvd.go
cmd/vfeed2nvd/vfeed2nvd.go
cmd/wfnconvert/wfnconvert.go
providers/fireeye/api/threat.go
providers/fireeye/api/vulnerability.go
providers/fireeye/schema/convertutils.go
providers/flexera/api/client.go
providers/idefense/api/client.go
providers/idefense/schema/convertutils.go
providers/lib/client/debug.go
providers/lib/runner/main.go
providers/rbs/api/client.go
providers/rbs/schema/convert.go
providers/redhat/api/client.go
providers/redhat/schema/convertutils.go
providers/snyk/api/client.go
providers/snyk/schema/convert.go
providers/snyk/schema/time.go
providers/vfeed/api/client.go
providers/vfeed/schema/convert_test.go
stats/stats.go

Unify log messages of the following binaries to GLOG format:
- csv2cpe
- fireeye2nvd
- flexera2nvd
- idefense2nvd
- rbs2nvd
- redhat2nvd
- snyk2nvd
- vfeed2nvd
- wfnconvert
From now on, they all use `flog` instead of `log` and `fmt.Fprint*(os.Stderr,...)`, so nvdtools' logs are more consistent.

Write logs in GLOG format

---

providers/rustsec/rustsec.go
providers/rustsec/rustsec_test.go

Fixes #160 
Update to RUSTSEC v3 advisory format.
Now the file contains toml and md parts, we extract those using regexp. 
https://regex101.com/r/yRhExR/1

Added RegExp to parse RustSec v3 advisory format

---

wfn/fsb.go
wfn/fsb_test.go

The panic was caused by malformed CPE names with unquoted '\' at the end of a fragment.
Before:
```
wfn $ go test
addSlashesAt(cpe:2.3:a:cisco:cisco_security_monitoring\, 16)
--- FAIL: TestUnbindFmtString (0.00s)
--- FAIL: TestUnbindFmtString/cpe:2.3:a:cisco:cisco_security_monitoring\ (0.00s)
panic: runtime error: index out of range [42] with length 42 [recovered]
panic: runtime error: index out of range [42] with length 42
goroutine 12 [running]:
testing.tRunner.func1.1(0x113f140, 0xc000012500)
/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc00011c900)
/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x113f140, 0xc000012500)
/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/facebookincubator/nvdtools/wfn.addSlashesAt(0x11582b0, 0x2a, 0x10, …
```

Fix index out of range panic in `wfn.UnbindFmtString()`

---

providers/redhat/feed.go
providers/redhat/package_feed.go

This change allows for users to iterate over the feed data to for instance, enumerate the CVEs or look for specific CVE data

Exporting redhat.Feed.Data

---

cvefeed/nvd/match_cpe.go
cvefeed/nvd/match_cve.go
cvefeed/nvd/match_node.go

When loading a feed I noticed a message such as:
```
2021/03/30 09:12:37 unknown operator, defaulting to OR: got ""
```
That's not really useful in the middle of a big feed of CVE data though. This
commit adds the CVE ID to the error message:
```
2021/03/30 17:08:24 CVE-2021-21166: unknown operator, defaulting to OR: got ""
```
(the NVD data for CVE-2021-21166 is fine, this was for an internally generated
feed/CVE ID)

nvd: Display the CVE ID in matching error messages

---

cvefeed/nvd/match_node.go
providers/redhat/package_feed.go
vulndb/custom.go
vulndb/export.go
vulndb/mysql/mysql.go
vulndb/snooze.go
vulndb/summary.go
vulndb/vendor.go

There were a few places that still used calles with the log package. Replacing with flog to use GLOG everywhere

Replacing remaining log calls with flog for GLOG formatting

---

cvss2/vector.go
cvss2/vector_test.go
cvss3/vector.go
cvss3/vector_test.go

Absorb semantics mean that, if the component is not defined in v1 but is in
v2, it will appear in the final result.
In some cases, it can be useful to only absorb vector components that are
defined in v1. AbsordIfDefined does just that.

[cvss] Introduce an AbsorbIfDefined() function

---

cvss2/vector.go
cvss2/vector_test.go
cvss3/vector.go
cvss3/vector_test.go

To compare for equility, we want to do a bit more than just comparing the
string representations of vectors. For some of the metrics, not specifying a
score is the same as specifying one of the other possible values.
For instance Remediation Level (RL):
> Assigning this value indicates there is insufficient information to choose
> one of the other values, and has no impact on the overall Temporal Score,
> i.e., it has the same effect on scoring as assigning Unavailable.
So not specifying RL or setting RL:X is the same as setting RL:U.

[cvss] Add functions to compare two CVSS vectors

---

providers/nvd/cpe.go

cpe.go is still using `http.DefaultClient` instead of `client.Default`, which
means overriding the client doesn't work when fetching the CPE dict.
Test: overrided `client.Default` to send http requests through a proxy and it worked.

[nvd] get the http client using the helper function

---

.github/workflows/tests.yaml
go.mod
go.sum
providers/snyk/api/client.go

github.com/dgrijalva/jwt-go package has been affected by CVE-2020-26160, the fix was deployed in v4.0.0-preview1, let's switch to it.

fix CVE-2020-26160

---

.github/workflows/tests.yaml
rpm/parse.go

This way, we can switch back and forth from string represtation to struct using String/Parse. Useful in case you want to serialise the struct or represent it in a human-readable way
Tried to do the conversion back and forth and obtained the same rpm.Package struct as a result
```
{Name:cups Label:{Epoch:1 Version:1.6.3 Release:51.el7} Arch:}
```

Added String method to convert rpm.Package structs to string form

---

.github/workflows/tests.yaml
cvefeed/cvecache.go
providers/redhat/package_feed_test.go
rpm/parse.go

What's done:
* change linter from deprecated golint to revive
* exclude SA5011 (deprecated strings.Title() call) -- the string
passed to it is guaranteed to be ASCII
* move nil-pointer check before first pointer dereferece in
cvefeed/cvecache.go
* proper declare-initialze syntax in
providers/redhat/package_feed_test.go:feedSummary()
* replace if strings.HasSuffix(..) { // manually trim suffix } with
strings.TrimSuffix() in rpm/parse.go

Fix linter.

---

providers/redhat/check/check_cve.go
providers/redhat/check/check_cve_test.go
providers/redhat/package_feed.go
providers/redhat/package_feed_test.go

Packages with uppercase letters were not properly indexed making some checks return false instead of true.
When nvdtools parse an RPM, the extracted producted is stored in lowercase, so we must use lowercase when extracting the package_name from the 'AffectedRelase' field of the redhat feed.

[redhat] Properly handle packages with uppercase letters

---

Makefile
providers/snyk/api/client.go

As detailed in the commits individually, the upstream API started to return replies unencoded, so it needs to be fixed

Snyk gzip encoding

---

vulndb/export.go

From https://pkg.go.dev/database/sql#Rows.Next:
```
Next prepares the next result row for reading with the Scan method. It returns true on success, or false if there is no next result row or an error happened while preparing it. Err should be consulted to distinguish between the two cases.
```
Due to not checking this, a user might hit timeout issues and believe that they had the complete resultset. This diffs returns an error in this case

[vulndb] Checking for errors after scanning all rows

---

.github/workflows/tests.yaml
cmd/rbs2nvd/rbs2nvd.go
cmd/redhat_filter/main_test.go
cmd/redhat_query/fetch-cve.go
cmd/redhat_query/fixed-cves.go
providers/idefense/schema/convert.go
providers/nvd/cpe_test.go
providers/nvd/src.go
providers/nvd/xrename.go
providers/redhat/check/check_pkg.go
providers/snyk/api/client.go
providers/vfeed/api/client.go
providers/vfeed/schema/convert_test.go
rpm/checker_test.go
rpm/compare.go
vulndb/export.go

When the rows object stops yielding rows and returns an error through the `Err()` method, it would then use `err` instead of `rows.Err()`, which at that point is nil, causing these errors to not be reported downstream.
Also, added this same check in the CSV export method

Fixing incorrect error variable returned

---

cvefeed/nvd/match_cpe.go

CVE-2019-19844
cpe: `cpe:2.3:a:djangoproject:django:-`
matchs:
```json
[
{
"children": [],
"operator": "OR",
"cpe_match": [
{
"cpe23Uri": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
"cpe_name": [],
"vulnerable": true,
"versionEndExcluding": "2.2.9",
"versionStartIncluding": "2.2"
},
{
"cpe23Uri": "cpe:2.3:a:djangoproject:django:3.0:*:*:*:*:*:*:*",
"cpe_name": [],
"vulnerable": true
},
{
"cpe23Uri": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
"cpe_name": [],
"vulnerable": true,
"versionEndExcluding": "1.11.27"
}
]
},
{
"children": [],
"operator": "OR",
"cpe_match": [
{
"cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
"cpe_name": [],
"vulnerable": true
},
{
"cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
"cpe_name": [],
"vulnerable": …
```

fix: cpe match na version
